name: babar
dependencies:
  - python
  - numpy
  - pandas
  - boto3
  - jupyterlab
  - plotly
  - pip:
    - tweepy
    - spotipy
    - dash
    - dash-renderer
    - dash-html-components
    - dash-core-components
    - sql_magic
    - python-dotenv
    - dash-table-experiments
